注：73和74上vi /etc/hosts添加
192.168.101.74  de9-74
192.168.101.73  de9-73

vi docker-compose.yml
version: '2'
services:
  gfs1:
    image: gluster/gluster-centos
    hostname: gfs1
    container_name: gfs1
    network_mode: host
    privileged: true
    extra_hosts:
      - "de9-73:192.168.101.73"  ##与外部主机名相同
      - "de9-74:192.168.101.74"
    volumes:
      - /var/maxwin/glusterfs/data:/var/lib/glusterd:rw
      - /var/maxwin/glusterfs/volume:/data:rw
      - /var/maxwin/glusterfs/logs:/var/log/glusterfs:rw
      - /var/maxwin/glusterfs/conf:/etc/glusterfs:rw
      - /dev:/dev:rw
      - /usr/share/zoneinfo/Asia/Taipei:/usr/share/zoneinfo/Asia/Taipei
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime/
      - /etc/timezone:/etc/timezone
    logging:
          driver: "json-file"
          options:
             max-size: "50m"
             max-file: "10"

----------------------------------
vi docker-compose.yml
version: '2'
services:
  gfs2:
    image: gluster/gluster-centos
    hostname: gfs2
    network_mode: host
    container_name: gfs2
    privileged: true
    extra_hosts:
      - "de9-73:192.168.101.73"  ##与外部主机名相同
      - "de9-74:192.168.101.74"
    volumes:
      - /var/maxwin/glusterfs/data:/var/lib/glusterd:rw
      - /var/maxwin/glusterfs/volume:/data:rw
      - /var/maxwin/glusterfs/logs:/var/log/glusterfs:rw
      - /var/maxwin/glusterfs/conf:/etc/glusterfs:rw
      - /dev:/dev:rw
      - /usr/share/zoneinfo/Asia/Taipei:/usr/share/zoneinfo/Asia/Taipei
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime/
      - /etc/timezone:/etc/timezone
    logging:
          driver: "json-file"
          options:
             max-size: "50m"
             max-file: "10"

